spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- PORT & SERVER CONFIGURATION ---
server.port=${SERVER_PORT:8080}

# Use environment variables for secrets and connection string.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/demo}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}

paystack.secret.key=${PAYSTACK_SECRET_KEY:}
paystack.base.url=${PAYSTACK_BASE_URL:https://api.paystack.co}
subscription.price.kobo=${SUBSCRIPTION_PRICE_KOBO:2000}