services:
  - type: web
    name: demo
    env: java
    buildCommand: apt-get install -y maven && mvn clean package -DskipTests
    startCommand: java -jar target/demo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-hidden-sky-at4jfgm2-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: Shinnelle