# Creates a new in-memory DB on every server restart (Great for beginners!)

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- PORT & SERVER CONFIGURATION ---
server.port=8080

# Use environment variables for secrets and connection string.
spring.datasource.url=jdbc:postgresql://ep-hidden-sky-at4jfgm2-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_3vGgQnaOId2h

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema 
firebase.service.account=classpath:skills-lock.json
